modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "lead_beyond"
version = "${version}"
displayName = "Lead Beyond"
authors = [
    "pkstDev",
    "Radekemia"
]
description = '''
Humans lead their way beyond the nature...

A railway-themed decoration mod for Dovecot railway server.
'''
[[dependencies.lead_beyond]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lead_beyond]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "AFTER"
side = "BOTH"
